export const CREATE_TASK = "CREATE_TUTORIAL";
export const RETRIEVE_TASKS = "RETRIEVE_TASKS";
export const UPDATE_TASK = "UPDATE_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const DELETE_ALL_TASKS = "DELETE_ALL_TASKS";